TURTLE_TRIVIA_QUESTIONS = {};
TURTLE_TRIVIA_ANSWERS1 = {};
TURTLE_TRIVIA_ANSWERS2 = {};
TURTLE_TRIVIA_ANSWERS3 = {};
TURTLE_TRIVIA_ANSWERS4 = {};
TURTLE_TRIVIA_ANSWERS5 = {};
TURTLE_TRIVIA_ANSWERS6 = {};
TURTLE_TRIVIA_ANSWERS7 = {};
TURTLE_TRIVIA_ANSWERS8 = {};

TURTLE_TRIVIA_QUESTIONS[1] = "What is the server mascott?";
TURTLE_TRIVIA_ANSWERS1[1] = "Turtle";

TURTLE_TRIVIA_QUESTIONS[2] = "What is the server mascott?";
TURTLE_TRIVIA_ANSWERS1[2] = "Turtle";

TURTLE_TRIVIA_QUESTIONS[3] = "What is the server mascott?";
TURTLE_TRIVIA_ANSWERS1[3] = "Turtle";

TURTLE_TRIVIA_QUESTIONS[4] = "What is the server mascott?";
TURTLE_TRIVIA_ANSWERS1[4] = "Turtle";